<?php $addresses = $this->getBillingAddress(); ?>
<br>

<div id="order-addresses">
    <div id="order-billing_address" class="box-left">
        <div class="entry-edit">

            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
            </div>

            <fieldset class="np">

                <div class="order-address" id="order-billing_address_fields">
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>

                                    <tr>
                                        <td class="label"><label>Street
                                                Address
                                                <span class="required">*</span></label></td>
                                        <td class="value">
                                            <div class="multi-input"><input name="billing[street]"
                                                    value="<?php echo $addresses['street']; ?>"
                                                    class=" input-text required-entry" type="text" disabled>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>Zip/Postal
                                                Code
                                                <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input name="billing[postcode]"
                                                value="<?php echo $addresses['postcode']; ?>"
                                                class=" required-entry input-text required-entry" type="text" disabled>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>State <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input name="billing[region]" value="<?php echo $addresses['region']; ?>"
                                                class=" required-entry input-text required-entry" type="text" disabled>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>City <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input name="billing[city]" value="<?php echo $addresses['city']; ?>"
                                                class=" required-entry input-text required-entry" type="text" disabled>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>Country<span class="required">*</span></label>
                                        </td>
                                        <td class="value">
                                            <input name="billing[country_id]"
                                                value="<?php echo $addresses['country_id']; ?>"
                                                class="required-entry input-text" type="text" disabled>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </fieldset>
        </div>
    </div>