<?php $orderData = $this->getOrder()->getItems();
// echo '<pre>';
// print_r($orderData->getData());
// die(); 
?>
<br>
<div id="order-items">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-cart">Cart Items</h4>
        </div>
    </div>

    <div class="grid" id="order-items_grid">
        <table cellspacing="0" class="data order-tables">
            <!-- <colgroup>
                    <col>
                    <col width="100">
                    <col width="40">
                    <col width="100">
                    <col width="80">
                    <col width="100">
                    <col width="80">
                </colgroup> -->
            <thead>
                <tr class="headings">
                    <th class="no-link">Id</th>
                    <th class="no-link">Product</th>
                    <th class="no-link">Qty</th>
                    <th class="no-link">Price</th>
                    <th class="no-link">Discount</th>
                    <th class="no-link">Base Price</th>
                </tr>
            </thead>

            <tbody>
                <?php if($orderData->getData()): ?>
                <?php foreach ($orderData->getData() as $order): ?>
                <tr>
                    <td class="empty-text a-center"><?php echo $order['order_item_id']; ?></td>
                    <td class="empty-text a-center"><?php echo $this->getProductName($order['product_id']); ?></td>
                    <td class="empty-text a-center"><?php echo $order['quantity']; ?></td>
                    <td class="empty-text a-center"><?php echo $order['price']; ?></td>
                    <td class="empty-text a-center"><?php echo $order['discount']; ?></td>
                    <td class="empty-text a-center"><?php echo $order['base_price']; ?></td>
                </tr>
                <?php endforeach; ?>

                <?php else: ?>
                <td class="empty-text a-center" colspan="100">Record Not Found</td>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
</div>
</form>