<?php 
    $paymentCode = $this->getOrder()->getPaymentMethodCode();
?>
<div id="order-methods">
    <div id="order-billing_method" class="box-left payments">
        <div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <div style="float: right;"></div>

                    <h4 class="fieldset-legend head-payment-method icon-head">Payment Method</h4>
                </div>
                <div class="fieldset">
                    <div id="order-billing_method_form">

                        <dl class="payment-methods">
                            <dt>
                                <label class="normal"><?php echo $paymentCode;?></label>
                            </dt>

                        </dl>
                    </div>

                </div>

            </div>
        </div>

    </div>

</div>