<?php $addresses = $this->getShippingAddress(); ?>
<div id="order-shipping_address" class="box-right">
    <div class="entry-edit" style="position: relative;">

        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend head-shipping-address">Shipping Address</h4>
        </div>

        <fieldset class="np">
            <div class="order-address" id="order-shipping_address_fields">
                <div class="content">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>

                                <tr>
                                    <td class="label"><label>Street Address
                                            <span class="required">*</span></label></td>
                                    <td class="value">
                                        <div class="multi-input"><input name="shipping[street]"
                                                value="<?php echo $addresses['street']; ?>"
                                                class="input-text required-entry" type="text" disabled>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label>Zip/Postal
                                            Code
                                            <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input name="shipping[postcode]" value="<?php echo $addresses['postcode']; ?>"
                                            class=" required-entry input-text required-entry" type="text" disabled>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label>State <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input name="shipping[region]" value="<?php echo $addresses['region']; ?>"
                                            class=" required-entry input-text required-entry" type="text" disabled>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label>City <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input name="shipping[city]" value="<?php echo $addresses['city']; ?>"
                                            class=" required-entry input-text required-entry" type="text" disabled>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label>Country<span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input name="shipping[country_id]"
                                            value="<?php echo $addresses['country_id']; ?>"
                                            class="required-entry input-text" type="text" disabled>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </fieldset>
    </div>
</div>