<?php 
$shippingCode = $this->getOrder()->getShippingMethodCode(); 
?>
<div id="order-shipping_method" class="box-right">
    <div>
        <div class="entry-edit" style="position: relative;">
            <div class="entry-edit-head">
                <div style="float: right;"></div>
                <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
            </div>
            <div class="fieldset">
                <div id="order-shipping-method-choose" style="">
                    <dl class="shipment-methods">
                        <dt><strong><?php //echo $shippingLabel; ?></strong></dt>
                        <dd>
                            <ul>
                                <li>
                                    <label class="normal">
                                        <?php echo $shippingCode; ?>
                                    </label>
                                </li>
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>