<?php $order = $this->getOrder(); 
// echo '<pre>';
// print_r($order);
// die();?>

<div class="content-header">
    <div id="order-header">
        <h3 class="icon-head head-sales-order">Invoice</h3>
    </div>
    <div class="form-buttons">
        <!-- <div class="form-buttons">
                <button id="submit_order_top_button" type="submit" class="scalable save">
                    <span>Place Order</span>
                </button>
            </div> -->
        <div class="form-buttons">
            <a href="<?php echo $this->getUrl('order/adminhtml_order/index'); ?>">
                <button type="button"><span>Cancel<span></button>
            </a>
        </div>
    </div>
</div>
<?php echo $this->getChild('account_invoice')->setOrder($order)->toHtml(); ?>
<?php //echo $this->getChildHtml('product'); ?>
<?php echo $this->getChild('orderitems_invoice')->setOrder($order)->toHtml() ?>
<?php echo $this->getChild('billingaddress_invoice')->setOrder($order)->toHtml(); ?>
<?php echo $this->getChild('shippingaddress_invoice')->setOrder($order)->toHtml(); ?>
<?php echo $this->getChild('payment_invoice')->setOrder($order)->toHtml(); ?>
<?php echo $this->getChild('shipping_invoice')->setOrder($order)->toHtml(); ?>
<?php echo $this->getChild('total_invoice')->setOrder($order)->toHtml(); ?>