<?php $customers = $this->getCustomers()->getData(); ?>
<form method="post">
    <div id="order-form_account">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend head-account">Select Customer</h4>
            </div>
            <div id="customer_account_fieds">
                <div class="fieldset " id="main">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label"><label for="customer">Customer <span
                                                class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <select class="form-control" name="customerId" onchange="customerSelect();">
                                            <option value="">Select Customer</option>
                                            <?php foreach ($customers as $key => $customer): ?>
                                            <option value=" <?= $customer['entity_id'] ?>"><?= $customer['name'] ?>
                                            </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
function customerSelect() {
    document.getElementById('data').style.display = "block";
    object.resetParam().setUrl('<?php echo $this->getUrl('*/*/getCart') ?>').setParams(jQuery('#cartForm')
        .serializeArray()).setMethod('POST').load();
}
</script>