<?php 
	$paymentMethods = $this->getPaymentMethods();
    
?>
<form id="paymentForm" method="post"
    action="<?php echo $this->getUrl('order/adminhtml_order_cart/savePaymentMethod'); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-methods">
        <div id="order-billing_method" class="box-left payments">
            <div>
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <div style="float: right;"></div>

                        <h4 class="fieldset-legend head-payment-method icon-head">Payment Method</h4>

                        <div class="form-buttons"><input type="submit" class="scalable add" value="Save">

                        </div>
                    </div>
                    <div class="fieldset">
                        <div id="order-billing_method_form">

                            <dl class="payment-methods">
                                <?php foreach($paymentMethods as $key => $value): ?>
                                <dt>
                                    <input value="<?php echo $value->getTitle(); ?>" type="radio" name="paymentmethod">
                                    <label class="normal"><?php echo $value->getTitle();?></label>

                                </dt>
                                <?php endforeach; ?>
                            </dl>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
</form>