<?php $shippingMethods = $this->getShippingMethods();
// echo '<pre>';
// print_r($shippingMethods);
// die(); ?>
<form id="shippingForm" method="post"
    action="<?php echo $this->getUrl('order/adminhtml_order_cart/saveShippingMethod'); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-shipping_method" class="box-right">
        <div>
            <div class="entry-edit" style="position: relative;">
                <div class="entry-edit-head">
                    <div style="float: right;"></div>
                    <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
                    <div class="form-buttons"><input type="submit" class="scalable add" value="Save"></div>
                </div>
                <div class="fieldset">
                    <div id="order-shipping-method-choose" style="">
                        <?php foreach ($shippingMethods as $key => $value): ?>
                        <dl class="shipment-methods">
                            <dt><strong><?php //echo $shippingLabel; ?></strong></dt>
                            <dd>
                                <ul>
                                    <li>
                                        <input name="shippingmethod" type="radio"
                                            value="<?php echo $key.''.$value->getConfigData('price'); ?>"
                                            id="s_method_<?php echo $shippingCode; ?>">
                                        <label class="normal">
                                            <?php echo $value->getConfigData('name').'    '.$value->getConfigData('price'); ?>

                                        </label>
                                    </li>
                                </ul>
                            </dd>
                        </dl>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>