<?php $customer = $this->getCart()->getCustomer(); ?>
<div id="order-form_account">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend head-account">Account Information</h4>
        </div>
        <div id="customer_account_fieds">
            <div class="fieldset " id="main">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label"><label for="group_id">Group <span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <input id="email" name="order[account][email]"
                                        value="<?php echo $customer->getFirstname().' '.$customer->getLastname(); ?>"
                                        class=" validate-email input-text" type="text" readonly>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="email">Email</label></td>
                                <td class="value">
                                    <input id="email" name="order[account][email]"
                                        value=<?php echo $customer->getEmail(); ?> class="validate-email input-text"
                                        type="text" readonly>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>