<?php 
	$paymentMethods = $this->getPaymentMethods();
    $paymentCode = $this->getCart()->getPaymentMethodCode();
?>
<form id="paymentForm" method="post"
    action="<?php echo $this->getUrl('order/adminhtml_order_cart/savePaymentMethod',['id' =>$this->getRequest()->getParam('id')]); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-methods">
        <div id="order-billing_method" class="box-left payments">
            <div>
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <div style="float: right;"></div>

                        <h4 class="fieldset-legend head-payment-method icon-head">Payment Method</h4>
                        <button type="submit" name="button" style="float: right;">Save</button>
                    </div>
                    <div class="fieldset">
                        <div id="order-billing_method_form">

                            <dl class="payment-methods">
                                <?php foreach($paymentMethods as $key => $value): ?>
                                <dt>
                                    <input value="<?php echo $value->getTitle(); ?>" type="radio" name="paymentmethod"
                                        <?php if($value->getTitle()==$paymentCode):?>checked<?php endif; ?>>
                                    <label class="normal"><?php echo $value->getTitle();?></label>

                                </dt>
                                <?php endforeach; ?>
                            </dl>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
</form>