<?php $shippingMethods = $this->getShippingMethods();
$shippingCode = $this->getCart()->getShippingMethodCode(); 
// echo '<pre>';
// print_r($shippingMethods);
// die(); 
?>
<form id="shippingForm" method="post"
    action="<?php echo $this->getUrl('order/adminhtml_order_cart/saveShippingMethod',['id' =>$this->getRequest()->getParam('id')]); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-shipping_method" class="box-right">
        <div>
            <div class="entry-edit" style="position: relative;">
                <div class="entry-edit-head">
                    <div style="float: right;"></div>
                    <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
                    <button type="submit" name="button" style="float: right;">Save</button>
                </div>
                <div class="fieldset">
                    <div id="order-shipping-method-choose" style="">
                        <?php foreach ($shippingMethods as $key => $value): ?>
                        <dl class="shipment-methods">
                            <dt><strong><?php //echo $shippingLabel; ?></strong></dt>
                            <dd>
                                <ul>
                                    <li>
                                        <input name="shippingmethod" type="radio"
                                            value="<?php echo $value->getId().'_'.$value->getConfigData('price'); ?>"
                                            <?php if($value->getId()==$shippingCode):?>checked<?php endif; ?>>
                                        <label class="normal">
                                            <?php echo $value->getConfigData('name').' '.$value->getConfigData('price'); ?>

                                        </label>
                                    </li>
                                </ul>
                            </dd>
                        </dl>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>